default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_PROD'] %>
  username: lite_bank_app
  password: <%= ENV['LITE_BANK_APP_DATABASE_PASSWORD'] %>
